name: Makefile

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Run Sever
      run: ./server.out Source/confi.json
    - name: Run Client
      run: ./client.out Source/confi.json
